<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>INF._5120.Arch0604.Infrastructure</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Files\" />
    <Folder Include="Migrations\" />
    <Folder Include="Services\" />
    <Folder Include="Persistence\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\INF.5120.Arch0604.Application\INF.5120.Arch0604.Application.csproj" />
    <ProjectReference Include="..\INF.5120.Arch0604.Domain\INF.5120.Arch0604.Domain.csproj" />
  </ItemGroup>

</Project>
